const mealPlan = require("../models/mealPlan");
const ForbiddenError = require("../errors/ForbiddenError");
const BadRequestError = require("../errors/BadRequestError");
const NotFoundError = require("../errors/NotFoundError");
const API_KEY = process.env.OPEN_AI_API_KEY;

//1. Generate meal plans for a user
module.exports.generateMealPlan = (req, res, next) => {
  userInput = req.body;
  owner = req.user._id;
  return fetch(`https://api.openai.com/v1/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are an AI sous chef that creates a 4 day meal plan in JSON format.
                    Respond ONLY with a valid JSON array like this:
                    [
                      { "mealDiet:" {Depending on the user input's choice beterrn Carnivor, Vegan,Omnivor, or Pescatarian}
                        "mealTitle": "Spaghetti Bolognese (a maxmimum of 2 words)",
                        "mealIcon: "🍝 (A single icon only)",
                        "mealInstructions": [
                          "⏱️ Cooking time : 20 minutes"
                          "Boil pasta until tender",
                          "Cook beef with sauce",
                          "Mix and serve hot"
                        ]
                      }
                    ]`,
        },
        {
          role: "user",
          content: ` My dietary preference is: ${userInput[0]}
                               My fridge contains: ${userInput[1].join(", ")}`,
        },
      ],
    }),
  })
    .then((openaiRes) => {
      if (!openaiRes.ok) {
        return openaiRes.text().then((text) => {
          return Promise.reject(`OpenAI error ${openaiRes.status}: ${text}`);
        });
      }
      return openaiRes.json();
    })
    .then((data) => {
      const content = data?.choices?.[0]?.message?.content;
      if (!content) {
        return Promise.reject("No content returned from OpenAI");
      }

      let meals;
      try {
        meals = JSON.parse(content);
      } catch (e) {
        return Promise.reject("OpenAI did not return valid JSON");
      }

      return meals;
    })
    .then((meals) => {
      meals.forEach((meal) => {
        mealPlan.create({
          mealDiet: meal.mealDiet,
          mealTitle: meal.mealTitle,
          mealIcon: meal.mealIcon,
          mealInstructions: meal.mealInstructions,
          owner: owner,
        });
      });
      return res.status(200).send({ mealsCreated: meals.length, meals });
    })
    .catch((err) => {
      return next(new BadRequestError(err));
    });
};
//2. Get all the meal plans generated by a user
module.exports.getUserMealPlan = (req, res, next) => {
  owner = req.user._id;
  mealPlan
    .findById(req.params.mealPlanId)
    .then((mealPlean) => {
      if (!mealPlan) {
        const err = new NotFoundError("Meal plan not found");
        return next(err);
      }
      if (mealPlan.owner.toString() !== owner) {
        const err = new ForbiddenError(
          "You cannot delete another user's meal plans"
        );
        return next(err);
      }

      return mealPlan
        .then(() => {
          return res.send("User's meal plan has been found");
        })
        .catch((err) => {
          return next(err);
        });
    })
    .catch((err) => {
      if ((err.name = "CastError")) {
        const error = new BadRequestError("Invalid ID Fromat");
        return next(error);
      }
      return next(err);
    });
};

//3. Delete a user meal plan (Add delete functionality to frontend as well)
module.exports.deleteUserMealPlanSingle = (req, res, next) => {};


