const mealPlan = require("../models/mealPlan");
const ForbiddenError = require("../errors/ForbiddenError");
const BadRequestError = require("../errors/BadRequestError");
const NotFoundError = require("../errors/NotFoundError");
const API_KEY = process.env.OPENAI_API_KEY;

//1. Generate meal plans for a user
module.exports.generateMealPlan = (req, res, next) => {
  // const owner = req.user?._id;
  const userInput = req.body;
  return fetch(`https://api.openai.com/v1/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are an AI sous chef that creates a 4 day meal plan in JSON format.
                    Respond ONLY with a valid JSON array like this:
                    [
                      { "mealDiet:" {Depending on the user input's choice beterrn Carnivor, Vegan,Omnivor, or Pescatarian}
                        "mealTitle": "Spaghetti Bolognese (a maxmimum of 2 words)",
                        "mealIcon: "🍝 (A single icon only)",
                        "mealInstructions": [
                          "⏱️ Cooking time : 20 minutes"
                          "Boil pasta until tender",
                          "Cook beef with sauce",
                          "Mix and serve hot"
                        ]
                      }
                    ]`,
        },
        {
          role: "user",
          content: ` My dietary preference is: ${userInput[0]}
                               My fridge contains: ${userInput[1].join(", ")}`,
        },
      ],
    }),
  })
    .then((openaiRes) => {
      if (!openaiRes.ok) {
        return openaiRes.text().then((text) => {
          return Promise.reject(`OpenAI error ${openaiRes.status}: ${text}`);
        });
      }
      return openaiRes.json();
    })
    .then((data) => {
      const content = data?.choices?.[0]?.message?.content;
      if (!content) {
        return Promise.reject("No content returned from OpenAI");
      }

      let meals;
      try {
        meals = JSON.parse(content);
      } catch (e) {
        return Promise.reject("OpenAI did not return valid JSON");
      }

      return res.status(200).send({ meals });
    })
    .catch((err) => {
      console.error(err);
    });
};

//2. Save a users meal plans aka create a mealplan schema

module.exports.saveUserMealPlans = (req, res, next) => {
  const owner = req.user._id;
  const {meals} = req.body;

  if (!Array.isArray(meals)) {
    return res
      .status(400)
      .send({ message: "Request body must be an array of meals" });
  }

  return Promise.all(
    meals.map((meal) =>
      mealPlan.create({
        mealDiet: meal.mealDiet,
        mealTitle: meal.mealTitle,
        mealIcon: meal.mealIcon,
        mealInstructions: meal.mealInstructions,
        owner,
      })
    )
  )
    .then((createdMeals) =>
      res.status(200).send({
        mealsCreated: meals.length,
        meals: createdMeals,
        saved: true,
      })
    )
    .catch((err) => {
      console.log(err);
    });
};

//3. Get all the meal plans generated by a user
module.exports.getUserMealPlans = (req, res, next) => {
  const owner = req.user._id;
  mealPlan
    .find({ owner }) //all plans for the specific user
    .sort({ createdAt: -1 }) //sort then newest first
    .then((meals) => {
      console.log(meals);
      return res.status(200).send(meals);
    });
};

//3. Delete a user's meal   (Add delete functionality to frontend as well)
module.exports.deleteUserMeal = (req, res, next) => {
  const owner = req.user._id;
  const mealId = req.params.mealId;
  //check if the meal plan exists
  //check if the meal plan's owner is the currently authorized user
  //delete meal plan
  mealPlan
    .findOneAndDelete({ _id: mealId, owner })
    .then((deletedMeal) => {
      if (!deletedMeal) {
        const err = new NotFoundError("Meal Plan could not be found");
        return next(err);
      }
      return res.status(200).send({
        message: `Deleted : ${deletedMeal.mealTitle}`,
        deletedMealId: deletedMeal._id
      });
    })
    .catch((err) => {
      if (err.name === "CastError") {
        const error = new BadRequestError("Invalid mealPlanId Format");
        return next(err);
      }
      return next(err);
    });
};
